M48
; DRILL file KiCad 10.0.1 date 2026-09-02T19:20:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-02T19:20:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.300
%
G90
G05
T1
X85.525Y-78.9
X85.525Y-125.1
X131.0Y-138.0
X143.6Y-138.0
T2
X103.7Y-138.1
X112.1Y-138.1
T3
X120.0Y-71.6
X120.0Y-136.7
M30
